### ISSUE TITLE
Prevenir flood do feed 

### ISSUE THREAD

**Issue by PTWJPL** [manthesepeasrock/Tascas-issues#8]
Consigo fazer check in no mesmo local infinitas vezes conseguindo fazer flood ao feed.

Sugestões:
- Limitar o mesmo local por X tempo 
OU
- Se for no mesmo dia e na mesma localização adicionas uma nova data ao cardview mostrando as várias datas que fez check-in naquele local e fazes update da posição da RecycleView para aparecer como novo na mesma

**Comment by manthesepeasrock** [comment]
fixed on version 0.2.760
