### ISSUE TITLE
Add follower

### ISSUE THREAD

**Issue by PTWJPL** [manthesepeasrock/Tascas-issues#9]
- Ao adicionar um follower nao recebo mensagem de confirmação
- No menu Social, depois de adicionar um follower a informação continua igual: Following(0) - não faz update

**Comment by manthesepeasrock** [comment]
- Notifications soon
- fixed on version 0.2.753

**Comment by manthesepeasrock** [comment]
toast informing user added or removed added on version 0.2.756
